name: Publish Docker image
on: [workflow_dispatch]
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      id-token: write
      attestations: write
    strategy:
      matrix:
        version: [13, 14, 15, 16]
    steps:
      - uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Generate Dockerfile
        run: sed 's/$VERSION/${{ matrix.version }}/g' Dockerfile > Dockerfile-${{ matrix.version }}
      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./Dockerfile-${{ matrix.version }}
          push: true
          tags: ghcr.io/significantbit/postgres-sv:${{ matrix.version }}
      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: ghcr.io/significantbit/postgres-sv
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true